# This workflow build and push a Docker container to Google Artifact Registry when the workflow is executed manually.
#
# Overview:
#
# 1. Authenticate to Google Cloud
# 2. Authenticate Docker to Artifact Registry
# 3. Build a docker container
# 4. Publish it to Google Artifact Registry
#
# To configure this workflow:
#
# 1. Ensure the required Google Cloud APIs are enabled: 
#    Artifact Registry    
#
# 2. Create and configure Workload Identity Federation for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Ensure the required IAM permissions are granted
#
#
#    Artifact Registry
#      roles/artifactregistry.write    (project or repository level)
#
#    NOTE: You should always follow the principle of least privilege when assigning IAM roles
#
# 4. Create GitHub secrets for WIF_PROVIDER and WIF_SERVICE_ACCOUNT
#
#
# NOTE: To use Google Container Registry instead, replace ${{ env.GAR_LOCATION }}-docker.pkg.dev with gcr.io
#
# For more support on how to run this workflow, please visit https://github.com/marketplace/actions/deploy-to-cloud-run
#
# Further reading:
#   Artifact Registry IAM permissions         - https://cloud.google.com/artifact-registry/docs/access-control#roles
#   Container Registry vs Artifact Registry   - https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry
#   Principle of least privilege              - https://cloud.google.com/blog/products/identity-security/dont-get-pwned-practicing-the-principle-of-least-privilege

name: Build and Deploy to Cloud Run

on:
  workflow_dispatch:

env:
  PROJECT_ID: blogity
  GAR_LOCATION: us-central1 
  SERVICE: cloud-run-source-deploy
  REGION: us-central1
  ENV: PROD

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: "auth"
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/550216339571/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider
          service_account: Blogity-service-account@blogity.iam.gserviceaccount.com
        
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
         username: 'oauth2accesstoken'
         password: '${{ steps.auth.outputs.access_token }}'
         registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ github.sha }}"
